[package]
name = "rustConwayProj"
version = "0.1.0"
authors = ["Admin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#coffee = { version = "0.4", features = ["opengl"] }
ggez = "0.5"
rand = "0.7.3"